<?php

/**
 * exceptionHandler function.
 * 
 * The function takes a parameter $e (which will be an object with information 
 * about the exception). This object $e will be automatically generated by PHP 
 * and passed to the function when the exception handler is triggered. To tell 
 * PHP to trigger this function when an exception occurs we use the built in 
 * method  set_exception_handler(). 
 * 
 * @author Petros Tamboutsiaris W21004471
 */
 
function exceptionHandler($e) {
   http_response_code(500);
   $output['message'] = "Internal Server Error";
   $output['details']['exception'] = $e->getMessage();
   $output['details']['file'] = $e->getFile();
   $output['details']['line'] = $e->getLine();
   echo json_encode($output);
   exit();
}